In [1]:
import pandas as pd

In [2]:
r1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Dominos", "Pizza Hut", "KFC", "Subway"],
    "city_id": [1, 1, 2, 3],
    "cost": [300, 400, 350, 250]
})
r1

   id       name  city_id  cost
0   1    Dominos        1   300
1   2  Pizza Hut        1   400
2   3        KFC        2   350
3   4     Subway        3   250

In [3]:
r2 = pd.DataFrame({
    "id": [4, 5, 6, 7],
    "name": ["Subway", "Biryani House", "Dosa Corner", "Cafe Mocha"],
    "city_id": [3, 2, 5, 1],
    "cost": [250, 450, 150, 200]
})
r2

   id           name  city_id  cost
0   4         Subway        3   250
1   5  Biryani House        2   450
2   6    Dosa Corner        5   150
3   7     Cafe Mocha        1   200

In [4]:
cities = pd.DataFrame({
    "city_id": [1, 2, 3, 4],
    "city": ["Bangalore", "Delhi", "Mumbai", "Pune"],
    "state": ["Karnataka", "Delhi", "Maharashtra", "Maharashtra"]
})
cities

   city_id       city        state
0        1  Bangalore    Karnataka
1        2      Delhi        Delhi
2        3     Mumbai  Maharashtra
3        4       Pune  Maharashtra

In [5]:
ratings = pd.DataFrame({
    "id": [1, 2, 3, 5, 8],
    "rating": [4.1, 3.9, 4.0, 4.4, 3.5]
})
ratings

   id  rating
0   1     4.1
1   2     3.9
2   3     4.0
3   5     4.4
4   8     3.5

In [6]:
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "id": [1, 1, 2, 3, 3, 5],
    "amount": [320, 280, 410, 360, 390, 470]
})
orders

   order_id  id  amount
0       101   1     320
1       102   1     280
2       103   2     410
3       104   3     360
4       105   3     390
5       106   5     470

In [7]:
pd.concat([r1, r2])

   id           name  city_id  cost
0   1        Dominos        1   300
1   2      Pizza Hut        1   400
2   3            KFC        2   350
3   4         Subway        3   250
0   4         Subway        3   250
1   5  Biryani House        2   450
2   6    Dosa Corner        5   150
3   7     Cafe Mocha        1   200

In [8]:
pd.concat([r1, r2], ignore_index=True)

   id           name  city_id  cost
0   1        Dominos        1   300
1   2      Pizza Hut        1   400
2   3            KFC        2   350
3   4         Subway        3   250
4   4         Subway        3   250
5   5  Biryani House        2   450
6   6    Dosa Corner        5   150
7   7     Cafe Mocha        1   200

In [9]:
pd.concat([r1, r2], keys=["batch1", "batch2"])

          id           name  city_id  cost
batch1 0   1        Dominos        1   300
       1   2      Pizza Hut        1   400
       2   3            KFC        2   350
       3   4         Subway        3   250
batch2 0   4         Subway        3   250
       1   5  Biryani House        2   450
       2   6    Dosa Corner        5   150
       3   7     Cafe Mocha        1   200

In [10]:
all_r = pd.concat([r1, r2], ignore_index=True)
all_r.drop_duplicates()

   id           name  city_id  cost
0   1        Dominos        1   300
1   2      Pizza Hut        1   400
2   3            KFC        2   350
3   4         Subway        3   250
5   5  Biryani House        2   450
6   6    Dosa Corner        5   150
7   7     Cafe Mocha        1   200

In [11]:
all_r = all_r.drop_duplicates().reset_index(drop=True)
all_r

   id           name  city_id  cost
0   1        Dominos        1   300
1   2      Pizza Hut        1   400
2   3            KFC        2   350
3   4         Subway        3   250
4   5  Biryani House        2   450
5   6    Dosa Corner        5   150
6   7     Cafe Mocha        1   200

In [12]:
extra = pd.DataFrame({"rating": [4.1, 3.9, 4.0, 3.8], "open": ["yes", "yes", "no", "yes"]})
pd.concat([r1, extra], axis=1)

   id       name  city_id  cost  rating open
0   1    Dominos        1   300     4.1  yes
1   2  Pizza Hut        1   400     3.9  yes
2   3        KFC        2   350     4.0   no
3   4     Subway        3   250     3.8  yes

In [13]:
extra2 = pd.DataFrame({"rating": [4.1, 3.9, 4.0]}, index=[2, 3, 4])
pd.concat([r1, extra2], axis=1)

    id       name  city_id   cost  rating
0  1.0    Dominos      1.0  300.0     NaN
1  2.0  Pizza Hut      1.0  400.0     NaN
2  3.0        KFC      2.0  350.0     4.1
3  4.0     Subway      3.0  250.0     3.9
4  NaN        NaN      NaN    NaN     4.0

In [14]:
pd.concat([r1, extra2], axis=1, join="inner")

   id    name  city_id  cost  rating
2   3     KFC        2   350     4.1
3   4  Subway        3   250     3.9

In [15]:
a = pd.DataFrame({"name": ["Dominos", "KFC"], "city": ["Bangalore", "Delhi"]})
b = pd.DataFrame({"name": ["Subway", "Pizza Hut"], "rating": [4.2, 3.9]})
pd.concat([a, b])

        name       city  rating
0    Dominos  Bangalore     NaN
1        KFC      Delhi     NaN
0     Subway        NaN     4.2
1  Pizza Hut        NaN     3.9

In [16]:
pd.concat([a, b], join="inner")

        name
0    Dominos
1        KFC
0     Subway
1  Pizza Hut

In [17]:
pd.merge(all_r, cities, on="city_id")

   id           name  city_id  cost       city        state
0   1        Dominos        1   300  Bangalore    Karnataka
1   2      Pizza Hut        1   400  Bangalore    Karnataka
2   3            KFC        2   350      Delhi        Delhi
3   4         Subway        3   250     Mumbai  Maharashtra
4   5  Biryani House        2   450      Delhi        Delhi
5   7     Cafe Mocha        1   200  Bangalore    Karnataka

In [18]:
pd.merge(all_r, cities, on="city_id", how="inner")

   id           name  city_id  cost       city        state
0   1        Dominos        1   300  Bangalore    Karnataka
1   2      Pizza Hut        1   400  Bangalore    Karnataka
2   3            KFC        2   350      Delhi        Delhi
3   4         Subway        3   250     Mumbai  Maharashtra
4   5  Biryani House        2   450      Delhi        Delhi
5   7     Cafe Mocha        1   200  Bangalore    Karnataka

In [19]:
pd.merge(all_r, cities, on="city_id", how="left")

   id           name  city_id  cost       city        state
0   1        Dominos        1   300  Bangalore    Karnataka
1   2      Pizza Hut        1   400  Bangalore    Karnataka
2   3            KFC        2   350      Delhi        Delhi
3   4         Subway        3   250     Mumbai  Maharashtra
4   5  Biryani House        2   450      Delhi        Delhi
5   6    Dosa Corner        5   150        NaN          NaN
6   7     Cafe Mocha        1   200  Bangalore    Karnataka

In [20]:
pd.merge(all_r, cities, on="city_id", how="right")

    id           name  city_id   cost       city        state
0  1.0        Dominos        1  300.0  Bangalore    Karnataka
1  2.0      Pizza Hut        1  400.0  Bangalore    Karnataka
2  7.0     Cafe Mocha        1  200.0  Bangalore    Karnataka
3  3.0            KFC        2  350.0      Delhi        Delhi
4  5.0  Biryani House        2  450.0      Delhi        Delhi
5  4.0         Subway        3  250.0     Mumbai  Maharashtra
6  NaN            NaN        4    NaN       Pune  Maharashtra

In [21]:
pd.merge(all_r, cities, on="city_id", how="outer")

    id           name  city_id   cost       city        state
0  1.0        Dominos        1  300.0  Bangalore    Karnataka
1  2.0      Pizza Hut        1  400.0  Bangalore    Karnataka
2  7.0     Cafe Mocha        1  200.0  Bangalore    Karnataka
3  3.0            KFC        2  350.0      Delhi        Delhi
4  5.0  Biryani House        2  450.0      Delhi        Delhi
5  4.0         Subway        3  250.0     Mumbai  Maharashtra
6  NaN            NaN        4    NaN       Pune  Maharashtra
7  6.0    Dosa Corner        5  150.0        NaN          NaN

In [22]:
pd.merge(all_r, ratings, on="id", how="left")

   id           name  city_id  cost  rating
0   1        Dominos        1   300     4.1
1   2      Pizza Hut        1   400     3.9
2   3            KFC        2   350     4.0
3   4         Subway        3   250     NaN
4   5  Biryani House        2   450     4.4
5   6    Dosa Corner        5   150     NaN
6   7     Cafe Mocha        1   200     NaN

In [23]:
pd.merge(all_r, ratings, on="id", how="outer", indicator=True)

   id           name  city_id   cost  rating      _merge
0   1        Dominos      1.0  300.0     4.1        both
1   2      Pizza Hut      1.0  400.0     3.9        both
2   3            KFC      2.0  350.0     4.0        both
3   4         Subway      3.0  250.0     NaN   left_only
4   5  Biryani House      2.0  450.0     4.4        both
5   6    Dosa Corner      5.0  150.0     NaN   left_only
6   7     Cafe Mocha      1.0  200.0     NaN   left_only
7   8            NaN      NaN    NaN     3.5  right_only

In [24]:
ratings2 = ratings.rename(columns={"id": "restaurant_id"})
ratings2

   restaurant_id  rating
0              1     4.1
1              2     3.9
2              3     4.0
3              5     4.4
4              8     3.5

In [25]:
pd.merge(all_r, ratings2, left_on="id", right_on="restaurant_id")

   id           name  city_id  cost  restaurant_id  rating
0   1        Dominos        1   300              1     4.1
1   2      Pizza Hut        1   400              2     3.9
2   3            KFC        2   350              3     4.0
3   5  Biryani House        2   450              5     4.4

In [26]:
pd.merge(all_r, ratings2, left_on="id", right_on="restaurant_id").drop(columns="restaurant_id")

   id           name  city_id  cost  rating
0   1        Dominos        1   300     4.1
1   2      Pizza Hut        1   400     3.9
2   3            KFC        2   350     4.0
3   5  Biryani House        2   450     4.4

In [27]:
x = pd.DataFrame({"id": [1, 2, 3], "rating": [4.1, 3.9, 4.0]})
y = pd.DataFrame({"id": [1, 2, 3], "rating": [4.3, 3.7, 4.2]})
pd.merge(x, y, on="id")

   id  rating_x  rating_y
0   1       4.1       4.3
1   2       3.9       3.7
2   3       4.0       4.2

In [28]:
pd.merge(x, y, on="id", suffixes=("_2023", "_2024"))

   id  rating_2023  rating_2024
0   1          4.1          4.3
1   2          3.9          3.7
2   3          4.0          4.2

In [29]:
p = pd.DataFrame({"city": ["Delhi", "Delhi", "Mumbai"], "cuisine": ["Chinese", "Indian", "Indian"], "count": [10, 25, 18]})
q = pd.DataFrame({"city": ["Delhi", "Delhi", "Mumbai"], "cuisine": ["Chinese", "Indian", "Indian"], "avg_cost": [300, 280, 350]})
pd.merge(p, q, on=["city", "cuisine"])

     city  cuisine  count  avg_cost
0   Delhi  Chinese     10       300
1   Delhi   Indian     25       280
2  Mumbai   Indian     18       350

In [30]:
pd.merge(r1.set_index("id"), ratings.set_index("id"), left_index=True, right_index=True)

         name  city_id  cost  rating
id
1     Dominos        1   300     4.1
2   Pizza Hut        1   400     3.9
3         KFC        2   350     4.0

In [31]:
pd.merge(r1.set_index("id"), ratings.set_index("id"), left_index=True, right_index=True, how="left")

         name  city_id  cost  rating
id
1     Dominos        1   300     4.1
2   Pizza Hut        1   400     3.9
3         KFC        2   350     4.0
4      Subway        3   250     NaN

In [32]:
r1i = r1.set_index("id")
ratingsi = ratings.set_index("id")
r1i.join(ratingsi)

         name  city_id  cost  rating
id
1     Dominos        1   300     4.1
2   Pizza Hut        1   400     3.9
3         KFC        2   350     4.0
4      Subway        3   250     NaN

In [33]:
r1i.join(ratingsi, how="inner")

         name  city_id  cost  rating
id
1     Dominos        1   300     4.1
2   Pizza Hut        1   400     3.9
3         KFC        2   350     4.0

In [34]:
r1i.join(ratingsi, how="outer")

         name  city_id   cost  rating
id
1     Dominos      1.0  300.0     4.1
2   Pizza Hut      1.0  400.0     3.9
3         KFC      2.0  350.0     4.0
4      Subway      3.0  250.0     NaN
5         NaN      NaN    NaN     4.4
8         NaN      NaN    NaN     3.5

In [35]:
r1.join(cities.set_index("city_id"), on="city_id")

   id       name  city_id  cost       city        state
0   1    Dominos        1   300  Bangalore    Karnataka
1   2  Pizza Hut        1   400  Bangalore    Karnataka
2   3        KFC        2   350      Delhi        Delhi
3   4     Subway        3   250     Mumbai  Maharashtra

In [36]:
left = pd.DataFrame({"id": [1, 2, 3], "score": [10, 20, 30]}).set_index("id")
right = pd.DataFrame({"id": [1, 2, 3], "score": [1, 2, 3]}).set_index("id")
left.join(right, lsuffix="_left", rsuffix="_right")

    score_left  score_right
id
1           10            1
2           20            2
3           30            3

In [37]:
merged = pd.merge(all_r, cities, on="city_id", how="left")
merged = pd.merge(merged, ratings, on="id", how="left")
merged

   id           name  city_id  cost       city        state  rating
0   1        Dominos        1   300  Bangalore    Karnataka     4.1
1   2      Pizza Hut        1   400  Bangalore    Karnataka     3.9
2   3            KFC        2   350      Delhi        Delhi     4.0
3   4         Subway        3   250     Mumbai  Maharashtra     NaN
4   5  Biryani House        2   450      Delhi        Delhi     4.4
5   6    Dosa Corner        5   150        NaN          NaN     NaN
6   7     Cafe Mocha        1   200  Bangalore    Karnataka     NaN

In [38]:
merged["city"] = merged["city"].fillna("Unknown")
merged["state"] = merged["state"].fillna("Unknown")
merged["rating"] = merged["rating"].fillna(merged["rating"].mean())
merged

   id           name  city_id  cost       city        state  rating
0   1        Dominos        1   300  Bangalore    Karnataka     4.1
1   2      Pizza Hut        1   400  Bangalore    Karnataka     3.9
2   3            KFC        2   350      Delhi        Delhi     4.0
3   4         Subway        3   250     Mumbai  Maharashtra     4.1
4   5  Biryani House        2   450      Delhi        Delhi     4.4
5   6    Dosa Corner        5   150    Unknown      Unknown     4.1
6   7     Cafe Mocha        1   200  Bangalore    Karnataka     4.1

In [39]:
merged.sort_values("rating", ascending=False)

   id           name  city_id  cost       city        state  rating
4   5  Biryani House        2   450      Delhi        Delhi     4.4
3   4         Subway        3   250     Mumbai  Maharashtra     4.1
0   1        Dominos        1   300  Bangalore    Karnataka     4.1
5   6    Dosa Corner        5   150    Unknown      Unknown     4.1
6   7     Cafe Mocha        1   200  Bangalore    Karnataka     4.1
2   3            KFC        2   350      Delhi        Delhi     4.0
1   2      Pizza Hut        1   400  Bangalore    Karnataka     3.9

In [40]:
order_totals = orders.groupby("id")["amount"].sum().reset_index()
order_totals

   id  amount
0   1     600
1   2     410
2   3     750
3   5     470

In [41]:
final = pd.merge(merged, order_totals, on="id", how="left")
final["amount"] = final["amount"].fillna(0)
final

   id           name  city_id  cost       city        state  rating  amount
0   1        Dominos        1   300  Bangalore    Karnataka     4.1   600.0
1   2      Pizza Hut        1   400  Bangalore    Karnataka     3.9   410.0
2   3            KFC        2   350      Delhi        Delhi     4.0   750.0
3   4         Subway        3   250     Mumbai  Maharashtra     4.1     0.0
4   5  Biryani House        2   450      Delhi        Delhi     4.4   470.0
5   6    Dosa Corner        5   150    Unknown      Unknown     4.1     0.0
6   7     Cafe Mocha        1   200  Bangalore    Karnataka     4.1     0.0

In [42]:
final.groupby("state")[["cost", "rating", "amount"]].mean()

              cost    rating      amount
state
Delhi        400.0  4.200000  610.000000
Karnataka    300.0  4.033333  336.666667
Maharashtra  250.0  4.100000    0.000000
Unknown      150.0  4.100000    0.000000

In [43]:
final.shape

(7, 8)