In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('train.csv')
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [3]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

**missing value handling**

In [4]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop(columns=["Cabin"])
df["Fare"] = df["Fare"].fillna(df.groupby("Pclass")["Fare"].transform("median"))
df = df.drop(columns=["Ticket", "Name", "PassengerId"])

**categorical encoding**

In [5]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})
df["Embarked"] = df["Embarked"].map({"S": 0, "C": 1, "Q": 2}) #one hot encoding
df["Pclass"] = df["Pclass"].astype("category")
df = df.drop_duplicates()
df

     Survived Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0      3    0  22.0      1      0   7.2500         0
1           1      1    1  38.0      1      0  71.2833         1
2           1      3    1  26.0      0      0   7.9250         0
3           1      1    1  35.0      1      0  53.1000         0
4           0      3    0  35.0      0      0   8.0500         0
..        ...    ...  ...   ...    ...    ...      ...       ...
885         0      3    1  39.0      0      5  29.1250         2
887         1      1    1  19.0      0      0  30.0000         0
888         0      3    1  28.0      1      2  23.4500         0
889         1      1    0  26.0      0      0  30.0000         1
890         0      3    0  32.0      0      0   7.7500         2

[775 rows x 8 columns]

**binning of ages**

In [7]:
age_bins = [0, 12, 18, 35, 60, 100]
age_labels = ["Child", "Teenager", "Young Adult", "Adult", "Senior"]
df["Age_Group"] = pd.cut(df["Age"], bins=age_bins, labels=age_labels)
df

     Survived Pclass  Sex   Age  SibSp  Parch     Fare  Embarked    Age_Group
0           0      3    0  22.0      1      0   7.2500         0  Young Adult
1           1      1    1  38.0      1      0  71.2833         1        Adult
2           1      3    1  26.0      0      0   7.9250         0  Young Adult
3           1      1    1  35.0      1      0  53.1000         0  Young Adult
4           0      3    0  35.0      0      0   8.0500         0  Young Adult
..        ...    ...  ...   ...    ...    ...      ...       ...          ...
885         0      3    1  39.0      0      5  29.1250         2        Adult
887         1      1    1  19.0      0      0  30.0000         0  Young Adult
888         0      3    1  28.0      1      2  23.4500         0  Young Adult
889         1      1    0  26.0      0      0  30.0000         1  Young Adult
890         0      3    0  32.0      0      0   7.7500         2  Young Adult

[775 rows x 9 columns]